codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        target: 75%
        threshold: 5%
        if_ci_failed: error

  changes:
    default:
      target: auto
      threshold: 1%

comment:
  layout: "header, diff, flags, components, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

  # Show coverage for all files
  branches:
    - master
    - main

# Service-specific flags
flags:
  unittests:
    paths:
      - services/
      - shared/
    carryforward: true

  user_service:
    paths:
      - services/user_service/
    carryforward: true

  inventory_service:
    paths:
      - services/inventory_service/
    carryforward: true

  order_service:
    paths:
      - services/order_service/
    carryforward: true

  payment_service:
    paths:
      - services/payment_service/
    carryforward: true

  integration_service:
    paths:
      - services/integration_service/
    carryforward: true

  frontend:
    paths:
      - frontend/
    carryforward: true

# Ignore patterns
ignore:
  - "**/*_test.rs"
  - "**/tests/**"
  - "**/benches/**"
  - "**/examples/**"
  - "target/**"
  - "**/main.rs" # Main files usually don't need coverage

  # Frontend ignore patterns
  - "frontend/node_modules/**"
  - "frontend/.svelte-kit/**"
  - "frontend/coverage/**"
  - "frontend/**/*.test.*"
  - "frontend/**/*.spec.*"
  - "frontend/e2e/**"

# GitHub integration
github_checks:
  annotations: true
