[dependencies]
chrono = {workspace = true}
jsonwebtoken = {workspace = true}
serde = {workspace = true}
shared_error = {workspace = true}
uuid = {workspace = true}

[package]
name = "shared_jwt"
authors.workspace = true
edition.workspace = true
version.workspace = true
