<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Textarea } from '$lib/components/ui/textarea';
	import { Checkbox } from '$lib/components/ui/checkbox';
	import * as Select from '$lib/components/ui/select';
	import * as Card from '$lib/components/ui/card';
	import type {
		CreatePriceListInput,
		UpdatePriceListInput,
		PriceList,
		PriceListType,
		BasedOn
	} from '$lib/types/pricing';

	interface Props {
		priceList?: PriceList | null;
		priceLists?: PriceList[];
		isSubmitting?: boolean;
		onSubmit: (data: CreatePriceListInput | UpdatePriceListInput) => void;
		onCancel: () => void;
	}

	let {
		priceList = null,
		priceLists = [],
		isSubmitting = false,
		onSubmit,
		onCancel
	}: Props = $props();

	const isEditing = $derived(!!priceList);

	// Form state
	let name = $state('');
	let code = $state('');
	let description = $state('');
	let currencyCode = $state('VND');
	let priceListType = $state<PriceListType>('sale');
	let basedOn = $state<BasedOn>('base_price');
	let parentPriceListId = $state<string | undefined>(undefined);
	let defaultPercentage = $state(0);
	let validFrom = $state('');
	let validTo = $state('');
	let priority = $state(100);
	let isDefault = $state(false);
	let isActive = $state(true);
	let alwaysValid = $state(true);

	// Initialization flag for edit mode
	let isInitialized = $state(false);

	// Validation errors
	let errors = $state<Record<string, string>>({});

	// Filter available parent price lists (exclude self)
	const availableParentLists = $derived(
		priceLists.filter(
			(pl) =>
				pl.priceListId !== priceList?.priceListId &&
				pl.priceListType === priceListType &&
				pl.isActive
		)
	);

	function formatDateForInput(date: Date): string {
		const d = new Date(date);
		return d.toISOString().split('T')[0];
	}

	function generateCode(text: string): string {
		return text
			.toUpperCase()
			.replace(/[^A-Z0-9]+/g, '_')
			.replace(/^_+|_+$/g, '')
			.slice(0, 20);
	}

	// Initialize form data from existing price list (for edit mode)
	$effect(() => {
		if (priceList && !isInitialized) {
			name = priceList.name;
			code = priceList.code;
			description = priceList.description ?? '';
			currencyCode = priceList.currencyCode;
			priceListType = priceList.priceListType;
			basedOn = priceList.basedOn;
			parentPriceListId = priceList.parentPriceListId;
			defaultPercentage = priceList.defaultPercentage;
			validFrom = priceList.validFrom ? formatDateForInput(priceList.validFrom) : '';
			validTo = priceList.validTo ? formatDateForInput(priceList.validTo) : '';
			priority = priceList.priority;
			isDefault = priceList.isDefault;
			isActive = priceList.isActive;
			alwaysValid = !priceList.validFrom && !priceList.validTo;
			isInitialized = true;
		}
	});

	// Auto-generate code when name changes (only for new price lists)
	const autoGeneratedCode = $derived(!isEditing && name && !code ? generateCode(name) : null);

	function handleNameChange(event: Event) {
		const input = event.target as HTMLInputElement;
		name = input.value;
		// Auto-generate code for new price lists when code is empty
		if (!isEditing && !code && name) {
			code = generateCode(name);
		}
	}

	function validate(): boolean {
		const newErrors: Record<string, string> = {};

		if (!name.trim()) {
			newErrors.name = 'Name is required';
		} else if (name.length > 100) {
			newErrors.name = 'Name must be 100 characters or less';
		}

		if (!code.trim()) {
			newErrors.code = 'Code is required';
		} else if (code.length > 20) {
			newErrors.code = 'Code must be 20 characters or less';
		} else if (!/^[A-Z0-9_-]+$/.test(code)) {
			newErrors.code =
				'Code must contain only uppercase letters, numbers, underscores, and hyphens';
		}

		if (basedOn === 'other_pricelist' && !parentPriceListId) {
			newErrors.parentPriceListId =
				'Parent price list is required when based on another price list';
		}

		if (!alwaysValid) {
			if (validFrom && validTo) {
				const from = new Date(validFrom);
				const to = new Date(validTo);
				if (from > to) {
					newErrors.validTo = 'End date must be after start date';
				}
			}
		}

		if (priority < 0) {
			newErrors.priority = 'Priority must be 0 or greater';
		}

		errors = newErrors;
		return Object.keys(newErrors).length === 0;
	}

	function handleSubmit() {
		if (!validate()) return;

		const data: CreatePriceListInput | UpdatePriceListInput = {
			name: name.trim(),
			code: code.trim(),
			description: description.trim() || undefined,
			currencyCode,
			priceListType,
			basedOn,
			parentPriceListId: basedOn === 'other_pricelist' ? parentPriceListId : undefined,
			defaultPercentage,
			validFrom: alwaysValid ? undefined : validFrom ? new Date(validFrom) : undefined,
			validTo: alwaysValid ? undefined : validTo ? new Date(validTo) : undefined,
			priority,
			isDefault,
			isActive
		};

		onSubmit(data);
	}

	function handlePriceListTypeChange(value: string | undefined) {
		if (value) {
			priceListType = value as PriceListType;
			// Reset parent when type changes
			parentPriceListId = undefined;
		}
	}

	function handleBasedOnChange(value: string | undefined) {
		if (value) {
			basedOn = value as BasedOn;
			if (value !== 'other_pricelist') {
				parentPriceListId = undefined;
			}
		}
	}

	function handleCurrencyChange(value: string | undefined) {
		if (value) {
			currencyCode = value;
		}
	}

	function handleParentChange(value: string | undefined) {
		parentPriceListId = value === 'none' ? undefined : value;
	}
</script>

<form
	onsubmit={(e) => {
		e.preventDefault();
		handleSubmit();
	}}
	class="space-y-6"
>
	<!-- Basic Information -->
	<Card.Root>
		<Card.Header>
			<Card.Title>Basic Information</Card.Title>
		</Card.Header>
		<Card.Content class="space-y-4">
			<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
				<div class="space-y-2">
					<Label for="name">Name *</Label>
					<Input
						id="name"
						value={name}
						oninput={handleNameChange}
						placeholder="e.g., Wholesale Pricing"
						class={errors.name ? 'border-destructive' : ''}
					/>
					{#if errors.name}
						<p class="text-sm text-destructive">{errors.name}</p>
					{/if}
				</div>

				<div class="space-y-2">
					<Label for="code">Code *</Label>
					<Input
						id="code"
						bind:value={code}
						placeholder="AUTO_GENERATED"
						class={errors.code ? 'border-destructive' : ''}
					/>
					{#if errors.code}
						<p class="text-sm text-destructive">{errors.code}</p>
					{/if}
				</div>
			</div>

			<div class="space-y-2">
				<Label for="description">Description</Label>
				<Textarea
					id="description"
					bind:value={description}
					placeholder="Optional description for this price list"
					rows={2}
				/>
			</div>

			<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
				<div class="space-y-2">
					<Label for="priceListType">Type *</Label>
					<Select.Root
						type="single"
						value={priceListType}
						onValueChange={handlePriceListTypeChange}
					>
						<Select.Trigger class="w-full">
							{priceListType === 'sale' ? 'Sale' : 'Purchase'}
						</Select.Trigger>
						<Select.Content>
							<Select.Item value="sale">Sale</Select.Item>
							<Select.Item value="purchase">Purchase</Select.Item>
						</Select.Content>
					</Select.Root>
				</div>

				<div class="space-y-2">
					<Label for="currency">Currency *</Label>
					<Select.Root type="single" value={currencyCode} onValueChange={handleCurrencyChange}>
						<Select.Trigger class="w-full">
							{currencyCode}
						</Select.Trigger>
						<Select.Content>
							<Select.Item value="VND">VND - Vietnamese Dong</Select.Item>
							<Select.Item value="USD">USD - US Dollar</Select.Item>
							<Select.Item value="EUR">EUR - Euro</Select.Item>
						</Select.Content>
					</Select.Root>
				</div>
			</div>
		</Card.Content>
	</Card.Root>

	<!-- Pricing Method -->
	<Card.Root>
		<Card.Header>
			<Card.Title>Pricing Method</Card.Title>
		</Card.Header>
		<Card.Content class="space-y-4">
			<div class="space-y-2">
				<Label for="basedOn">Based On *</Label>
				<Select.Root type="single" value={basedOn} onValueChange={handleBasedOnChange}>
					<Select.Trigger class="w-full">
						{#if basedOn === 'fixed'}
							Fixed prices (set specific prices for each product)
						{:else if basedOn === 'base_price'}
							Base price with adjustment
						{:else}
							Another price list
						{/if}
					</Select.Trigger>
					<Select.Content>
						<Select.Item value="fixed">Fixed prices</Select.Item>
						<Select.Item value="base_price">Base price with adjustment</Select.Item>
						<Select.Item value="other_pricelist">Another price list</Select.Item>
					</Select.Content>
				</Select.Root>
			</div>

			{#if basedOn === 'other_pricelist'}
				<div class="space-y-2">
					<Label for="parentPriceList">Parent Price List *</Label>
					<Select.Root
						type="single"
						value={parentPriceListId ?? 'none'}
						onValueChange={handleParentChange}
					>
						<Select.Trigger
							class={errors.parentPriceListId ? 'w-full border-destructive' : 'w-full'}
						>
							{#if parentPriceListId}
								{availableParentLists.find((pl) => pl.priceListId === parentPriceListId)?.name ??
									'Select price list'}
							{:else}
								Select price list
							{/if}
						</Select.Trigger>
						<Select.Content>
							{#each availableParentLists as pl (pl.priceListId)}
								<Select.Item value={pl.priceListId}>
									{pl.name} ({pl.code})
								</Select.Item>
							{:else}
								<Select.Item value="none" disabled>No available price lists</Select.Item>
							{/each}
						</Select.Content>
					</Select.Root>
					{#if errors.parentPriceListId}
						<p class="text-sm text-destructive">{errors.parentPriceListId}</p>
					{/if}
				</div>
			{/if}

			{#if basedOn !== 'fixed'}
				<div class="space-y-2">
					<Label for="defaultPercentage">Default Adjustment (%)</Label>
					<div class="flex items-center gap-2">
						<Input
							id="defaultPercentage"
							type="number"
							bind:value={defaultPercentage}
							class="w-32"
						/>
						<span class="text-sm text-muted-foreground">
							{#if defaultPercentage < 0}
								(Discount: {Math.abs(defaultPercentage)}% off)
							{:else if defaultPercentage > 0}
								(Markup: +{defaultPercentage}%)
							{:else}
								(No change)
							{/if}
						</span>
					</div>
					<p class="text-xs text-muted-foreground">Negative = discount, Positive = markup</p>
				</div>
			{/if}
		</Card.Content>
	</Card.Root>

	<!-- Validity -->
	<Card.Root>
		<Card.Header>
			<Card.Title>Validity</Card.Title>
		</Card.Header>
		<Card.Content class="space-y-4">
			<div class="flex items-center gap-2">
				<Checkbox id="alwaysValid" bind:checked={alwaysValid} />
				<Label for="alwaysValid" class="font-normal">Always valid (no date restrictions)</Label>
			</div>

			{#if !alwaysValid}
				<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
					<div class="space-y-2">
						<Label for="validFrom">Valid From</Label>
						<Input id="validFrom" type="date" bind:value={validFrom} />
					</div>

					<div class="space-y-2">
						<Label for="validTo">Valid To</Label>
						<Input
							id="validTo"
							type="date"
							bind:value={validTo}
							class={errors.validTo ? 'border-destructive' : ''}
						/>
						{#if errors.validTo}
							<p class="text-sm text-destructive">{errors.validTo}</p>
						{/if}
					</div>
				</div>
			{/if}
		</Card.Content>
	</Card.Root>

	<!-- Settings -->
	<Card.Root>
		<Card.Header>
			<Card.Title>Settings</Card.Title>
		</Card.Header>
		<Card.Content class="space-y-4">
			<div class="space-y-2">
				<Label for="priority">Priority</Label>
				<div class="flex items-center gap-2">
					<Input
						id="priority"
						type="number"
						bind:value={priority}
						min={0}
						class={errors.priority ? 'w-32 border-destructive' : 'w-32'}
					/>
					<span class="text-sm text-muted-foreground"> Lower number = higher priority </span>
				</div>
				{#if errors.priority}
					<p class="text-sm text-destructive">{errors.priority}</p>
				{/if}
			</div>

			<div class="flex flex-col gap-3 sm:flex-row sm:gap-6">
				<div class="flex items-center gap-2">
					<Checkbox id="isActive" bind:checked={isActive} />
					<Label for="isActive" class="font-normal">Active</Label>
				</div>

				{#if priceListType === 'sale'}
					<div class="flex items-center gap-2">
						<Checkbox id="isDefault" bind:checked={isDefault} />
						<Label for="isDefault" class="font-normal">Set as default price list</Label>
					</div>
				{/if}
			</div>
		</Card.Content>
	</Card.Root>

	<!-- Actions -->
	<div class="flex justify-end gap-3">
		<Button type="button" variant="outline" onclick={onCancel} disabled={isSubmitting}>
			Cancel
		</Button>
		<Button type="submit" disabled={isSubmitting}>
			{#if isSubmitting}
				Saving...
			{:else}
				{isEditing ? 'Update Price List' : 'Create Price List'}
			{/if}
		</Button>
	</div>
</form>
