openapi: 3.1.0
info:
  title: Inventory Service API
  description: Multi-tenant inventory management and warehouse operations service
  contact:
    name: Anthill Team
    email: tymon3568@gmail.com
  license:
    name: ''
  version: 0.1.0
servers:
- url: http://localhost:8001
  description: Local development server
paths: {}
components:
  schemas:
    CreateLotSerialRequest:
      type: object
      required:
      - product_id
      - tracking_type
      - status
      properties:
        expiry_date:
          type:
          - string
          - 'null'
          format: date-time
        initial_quantity:
          type:
          - integer
          - 'null'
          format: int64
        lot_number:
          type:
          - string
          - 'null'
        product_id:
          type: string
          format: uuid
        remaining_quantity:
          type:
          - integer
          - 'null'
          format: int64
        serial_number:
          type:
          - string
          - 'null'
        status:
          $ref: '#/components/schemas/LotSerialStatus'
        tracking_type:
          $ref: '#/components/schemas/LotSerialTrackingType'
    CreatePickingMethodRequest:
      type: object
      description: Request DTO for creating a new picking method
      required:
      - name
      - methodType
      - warehouseId
      - config
      properties:
        config:
          description: Method configuration (JSON)
        description:
          type:
          - string
          - 'null'
          description: Optional description
        isDefault:
          type:
          - boolean
          - 'null'
          description: Whether this should be the default method
        methodType:
          type: string
          description: Picking method type
        name:
          type: string
          description: Method name
        warehouseId:
          type: string
          format: uuid
          description: Warehouse ID this method applies to
    ListLotSerialsQuery:
      type: object
      properties:
        status:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/LotSerialStatus'
        tracking_type:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/LotSerialTrackingType'
    LotSerial:
      type: object
      required:
      - lot_serial_id
      - tenant_id
      - product_id
      - tracking_type
      - status
      - created_by
      - created_at
      - updated_at
      properties:
        created_at:
          type: string
          format: date-time
        created_by:
          type: string
          format: uuid
        deleted_at:
          type:
          - string
          - 'null'
          format: date-time
        expiry_date:
          type:
          - string
          - 'null'
          format: date-time
        initial_quantity:
          type:
          - integer
          - 'null'
          format: int64
        location_id:
          type:
          - string
          - 'null'
          format: uuid
        lot_number:
          type:
          - string
          - 'null'
        lot_serial_id:
          type: string
          format: uuid
        product_id:
          type: string
          format: uuid
        remaining_quantity:
          type:
          - integer
          - 'null'
          format: int64
        serial_number:
          type:
          - string
          - 'null'
        status:
          $ref: '#/components/schemas/LotSerialStatus'
        tenant_id:
          type: string
          format: uuid
        tracking_type:
          $ref: '#/components/schemas/LotSerialTrackingType'
        updated_at:
          type: string
          format: date-time
        updated_by:
          type:
          - string
          - 'null'
          format: uuid
        warehouse_id:
          type:
          - string
          - 'null'
          format: uuid
    LotSerialLifecycle:
      type: object
      required:
      - lot_serial
      - stock_moves
      - quality_checks
      properties:
        coa_link:
          type:
          - string
          - 'null'
          description: 'TODO: Populate from quality documents or attachments'
        current_location_code:
          type:
          - string
          - 'null'
          description: 'TODO: Populate from location table using lot_serial.location_id'
        current_warehouse_name:
          type:
          - string
          - 'null'
          description: 'TODO: Populate from warehouse table using lot_serial.location_id'
        lot_serial:
          $ref: '#/components/schemas/LotSerial'
        purchase_order_number:
          type:
          - string
          - 'null'
          description: 'TODO: Populate from purchase order table'
        quality_checks:
          type: array
          items: {}
          description: 'TODO: Populate from quality_checks table or related records'
        stock_moves:
          type: array
          items:
            $ref: '#/components/schemas/StockMove'
        supplier_name:
          type:
          - string
          - 'null'
          description: 'TODO: Populate from supplier table via purchase order'
    LotSerialStatus:
      type: string
      enum:
      - active
      - expired
      - quarantined
      - disposed
      - reserved
    LotSerialTrackingType:
      type: string
      enum:
      - lot
      - serial
    PaginationInfo:
      type: object
      required:
      - page
      - pageSize
      - totalItems
      - totalPages
      - hasNext
      - hasPrev
      properties:
        hasNext:
          type: boolean
        hasPrev:
          type: boolean
        page:
          type: integer
          format: int32
          minimum: 0
        pageSize:
          type: integer
          format: int32
          minimum: 0
        totalItems:
          type: integer
          format: int64
          minimum: 0
        totalPages:
          type: integer
          format: int32
          minimum: 0
    PickingMethodResponse:
      type: object
      description: Picking method response DTO
      required:
      - methodId
      - tenantId
      - name
      - methodType
      - warehouseId
      - config
      - isActive
      - isDefault
      - createdAt
      - updatedAt
      properties:
        config:
          description: Configuration
        createdAt:
          type: string
          format: date-time
          description: Timestamps
        description:
          type:
          - string
          - 'null'
        isActive:
          type: boolean
          description: Status flags
        isDefault:
          type: boolean
        methodId:
          type: string
          format: uuid
          description: Method ID
        methodType:
          type: string
          description: Method type
        name:
          type: string
          description: Method metadata
        tenantId:
          type: string
          format: uuid
          description: Tenant ID
        updatedAt:
          type: string
          format: date-time
        warehouseId:
          type: string
          format: uuid
          description: Warehouse ID
    QuarantineResponse:
      type: object
      required:
      - quarantined_count
      properties:
        quarantined_count:
          type: integer
          format: int64
    StockMove:
      type: object
      required:
      - move_id
      - tenant_id
      - product_id
      - move_type
      - quantity
      - reference_type
      - reference_id
      - idempotency_key
      - move_date
      - created_at
      properties:
        batch_info: {}
        created_at:
          type: string
          format: date-time
        destination_location_id:
          type:
          - string
          - 'null'
          format: uuid
        idempotency_key:
          type: string
        lot_serial_id:
          type:
          - string
          - 'null'
          format: uuid
        metadata: {}
        move_date:
          type: string
          format: date-time
        move_id:
          type: string
          format: uuid
        move_reason:
          type:
          - string
          - 'null'
        move_type:
          type: string
        product_id:
          type: string
          format: uuid
        quantity:
          type: integer
          format: int64
        reference_id:
          type: string
          format: uuid
        reference_type:
          type: string
        source_location_id:
          type:
          - string
          - 'null'
          format: uuid
        tenant_id:
          type: string
          format: uuid
        total_cost:
          type:
          - integer
          - 'null'
          format: int64
        unit_cost:
          type:
          - integer
          - 'null'
          format: int64
    UpdatePickingMethodRequest:
      type: object
      description: Request DTO for updating a picking method
      properties:
        config:
          description: Method configuration (JSON)
        description:
          type:
          - string
          - 'null'
          description: Description
        isActive:
          type:
          - boolean
          - 'null'
          description: Whether method is active
        isDefault:
          type:
          - boolean
          - 'null'
          description: Whether this should be the default method
        name:
          type:
          - string
          - 'null'
          description: Method name
