[dependencies]
config = {workspace = true}
dotenvy = {workspace = true}
serde = {workspace = true}

[package]
name = "shared_config"
authors.workspace = true
edition.workspace = true
version.workspace = true
