[dependencies]
chrono = {workspace = true}
serde = {workspace = true}
uuid = {workspace = true}

[package]
name = "shared_types"
authors.workspace = true
edition.workspace = true
version.workspace = true
