[dependencies]
shared_error = {workspace = true}
sqlx = {workspace = true}
tracing = {workspace = true}

[package]
name = "shared_db"
authors.workspace = true
edition.workspace = true
version.workspace = true
