[package]
name = "shared_db"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
sqlx = { workspace = true }
shared_error = { workspace = true }
tracing = { workspace = true }
